version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: lab4_mysql
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    ports:
      - "3308:3306"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql

  php:
    build: ./app
    container_name: lab4_php
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:stable
    container_name: lab4_nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html:ro
      - ./.nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

volumes:
  dbdata:
  